package me.bomb.indicators;

import org.bukkit.entity.EntityType;

enum LangMsg {
	INDICATOR_ENTITY_UNKNOWN_HEAL("indicator.heal.unknown",Type.HEAL),
	INDICATOR_ENTITY_PLAYER_HEAL("indicator.heal.player",Type.HEAL),
	INDICATOR_ENTITY_BAT_HEAL("indicator.heal.bat",Type.HEAL),
	INDICATOR_ENTITY_BEE_HEAL("indicator.heal.bee",Type.HEAL),
	INDICATOR_ENTITY_BLAZE_HEAL("indicator.heal.blaze",Type.HEAL),
	INDICATOR_ENTITY_CAT_HEAL("indicator.heal.cat",Type.HEAL),
	INDICATOR_ENTITY_CAVE_SPIDER_HEAL("indicator.heal.cavespider",Type.HEAL),
	INDICATOR_ENTITY_CHICKEN_HEAL("indicator.heal.chicken",Type.HEAL),
	INDICATOR_ENTITY_COD_HEAL("indicator.heal.cod",Type.HEAL),
	INDICATOR_ENTITY_COW_HEAL("indicator.heal.cow",Type.HEAL),
	INDICATOR_ENTITY_CREEPER_HEAL("indicator.heal.creeper",Type.HEAL),
	INDICATOR_ENTITY_DOLPHIN_HEAL("indicator.heal.dolphin",Type.HEAL),
	INDICATOR_ENTITY_DONKEY_HEAL("indicator.heal.donkey",Type.HEAL),
	INDICATOR_ENTITY_DROWNED_HEAL("indicator.heal.drowned",Type.HEAL),
	INDICATOR_ENTITY_ELDER_GUARDIAN_HEAL("indicator.heal.elderguardian",Type.HEAL),
	INDICATOR_ENTITY_ENDER_DRAGON_HEAL("indicator.heal.enderdragon",Type.HEAL),
	INDICATOR_ENTITY_ENDERMAN_HEAL("indicator.heal.enderman",Type.HEAL),
	INDICATOR_ENTITY_ENDERMITE_HEAL("indicator.heal.endermite",Type.HEAL),
	INDICATOR_ENTITY_EVOKER_HEAL("indicator.heal.evoker",Type.HEAL),
	INDICATOR_ENTITY_FOX_HEAL("indicator.heal.fox",Type.HEAL),
	INDICATOR_ENTITY_GHAST_HEAL("indicator.heal.ghast",Type.HEAL),
	INDICATOR_ENTITY_GIANT_HEAL("indicator.heal.giant",Type.HEAL),
	INDICATOR_ENTITY_GUARDIAN_HEAL("indicator.heal.guardian",Type.HEAL),
	INDICATOR_ENTITY_HOGLIN_HEAL("indicator.heal.hoglin",Type.HEAL),
	INDICATOR_ENTITY_HORSE_HEAL("indicator.heal.horse",Type.HEAL),
	INDICATOR_ENTITY_HUSK_HEAL("indicator.heal.husk",Type.HEAL),
	INDICATOR_ENTITY_ILLUSIONER_HEAL("indicator.heal.illusioner",Type.HEAL),
	INDICATOR_ENTITY_IRON_GOLEM_HEAL("indicator.heal.irongolem",Type.HEAL),
	INDICATOR_ENTITY_LLAMA_HEAL("indicator.heal.llama",Type.HEAL),
	INDICATOR_ENTITY_MAGMA_CUBE_HEAL("indicator.heal.magmacube",Type.HEAL),
	INDICATOR_ENTITY_MULE_HEAL("indicator.heal.mule",Type.HEAL),
	INDICATOR_ENTITY_MUSHROOM_COW_HEAL("indicator.heal.mushroomcow",Type.HEAL),
	INDICATOR_ENTITY_OCELOT_HEAL("indicator.heal.ocelot",Type.HEAL),
	INDICATOR_ENTITY_PANDA_HEAL("indicator.heal.panda",Type.HEAL),
	INDICATOR_ENTITY_PARROT_HEAL("indicator.heal.parrot",Type.HEAL),
	INDICATOR_ENTITY_PHANTOM_HEAL("indicator.heal.phantom",Type.HEAL),
	INDICATOR_ENTITY_PIG_HEAL("indicator.heal.pig",Type.HEAL),
	INDICATOR_ENTITY_PIGLIN_HEAL("indicator.heal.piglin",Type.HEAL),
	INDICATOR_ENTITY_PIGLIN_BRUTE_HEAL("indicator.heal.piglinbrute",Type.HEAL),
	INDICATOR_ENTITY_PIG_ZOMBIE_HEAL("indicator.heal.pigzombie",Type.HEAL),
	INDICATOR_ENTITY_PILLAGER_HEAL("indicator.heal.pillager",Type.HEAL),
	INDICATOR_ENTITY_POLAR_BEAR_HEAL("indicator.heal.polarbear",Type.HEAL),
	INDICATOR_ENTITY_PUFFERFISH_HEAL("indicator.heal.pufferfish",Type.HEAL),
	INDICATOR_ENTITY_RABBIT_HEAL("indicator.heal.rabbit",Type.HEAL),
	INDICATOR_ENTITY_RAVAGER_HEAL("indicator.heal.ravager",Type.HEAL),
	INDICATOR_ENTITY_SALMON_HEAL("indicator.heal.salmon",Type.HEAL),
	INDICATOR_ENTITY_SHEEP_HEAL("indicator.heal.sheep",Type.HEAL),
	INDICATOR_ENTITY_SHULKER_HEAL("indicator.heal.shulker",Type.HEAL),
	INDICATOR_ENTITY_SILVERFISH_HEAL("indicator.heal.silverfish",Type.HEAL),
	INDICATOR_ENTITY_SKELETON_HEAL("indicator.heal.skeleton",Type.HEAL),
	INDICATOR_ENTITY_SKELETON_HORSE_HEAL("indicator.heal.skeletonhorse",Type.HEAL),
	INDICATOR_ENTITY_SLIME_HEAL("indicator.heal.slime",Type.HEAL),
	INDICATOR_ENTITY_SNOWMAN_HEAL("indicator.heal.snowman",Type.HEAL),
	INDICATOR_ENTITY_SPIDER_HEAL("indicator.heal.spider",Type.HEAL),
	INDICATOR_ENTITY_SQUID_HEAL("indicator.heal.squid",Type.HEAL),
	INDICATOR_ENTITY_STRAY_HEAL("indicator.heal.stray",Type.HEAL),
	INDICATOR_ENTITY_STRIDER_HEAL("indicator.heal.strider",Type.HEAL),
	INDICATOR_ENTITY_TRADER_LLAMA_HEAL("indicator.heal.traderllama",Type.HEAL),
	INDICATOR_ENTITY_TROPICAL_FISH_HEAL("indicator.heal.tropicalfish",Type.HEAL),
	INDICATOR_ENTITY_TURTLE_HEAL("indicator.heal.turtle",Type.HEAL),
	INDICATOR_ENTITY_VEX_HEAL("indicator.heal.vex",Type.HEAL),
	INDICATOR_ENTITY_VILLAGER_HEAL("indicator.heal.villager",Type.HEAL),
	INDICATOR_ENTITY_VINDICATOR_HEAL("indicator.heal.vindicator",Type.HEAL),
	INDICATOR_ENTITY_WANDERING_TRADER_HEAL("indicator.heal.wanderingtrader",Type.HEAL),
	INDICATOR_ENTITY_WITCH_HEAL("indicator.heal.witch",Type.HEAL),
	INDICATOR_ENTITY_WITHER_HEAL("indicator.heal.wither",Type.HEAL),
	INDICATOR_ENTITY_WITHER_SKELETON_HEAL("indicator.heal.witherskeleton",Type.HEAL),
	INDICATOR_ENTITY_WOLF_HEAL("indicator.heal.wolf",Type.HEAL),
	INDICATOR_ENTITY_ZOGLIN_HEAL("indicator.heal.zoglin",Type.HEAL),
	INDICATOR_ENTITY_ZOMBIE_HEAL("indicator.heal.zombie",Type.HEAL),
	INDICATOR_ENTITY_ZOMBIE_HORSE_HEAL("indicator.heal.zombiehorse",Type.HEAL),
	INDICATOR_ENTITY_ZOMBIE_VILLAGER_HEAL("indicator.heal.zombievillager",Type.HEAL),
	INDICATOR_ENTITY_ZOMBIFIED_PIGLIN_HEAL("indicator.heal.zombifiedpiglin",Type.HEAL),
	INDICATOR_ENTITY_UNKNOWN_DAMAGE("indicator.damage.unknown",Type.DAMAGE),
	INDICATOR_ENTITY_PLAYER_DAMAGE("indicator.damage.player",Type.DAMAGE),
	INDICATOR_ENTITY_BAT_DAMAGE("indicator.damage.bat",Type.DAMAGE),
	INDICATOR_ENTITY_BEE_DAMAGE("indicator.damage.bee",Type.DAMAGE),
	INDICATOR_ENTITY_BLAZE_DAMAGE("indicator.damage.blaze",Type.DAMAGE),
	INDICATOR_ENTITY_CAT_DAMAGE("indicator.damage.cat",Type.DAMAGE),
	INDICATOR_ENTITY_CAVE_SPIDER_DAMAGE("indicator.damage.cavespider",Type.DAMAGE),
	INDICATOR_ENTITY_CHICKEN_DAMAGE("indicator.damage.chicken",Type.DAMAGE),
	INDICATOR_ENTITY_COD_DAMAGE("indicator.damage.cod",Type.DAMAGE),
	INDICATOR_ENTITY_COW_DAMAGE("indicator.damage.cow",Type.DAMAGE),
	INDICATOR_ENTITY_CREEPER_DAMAGE("indicator.damage.creeper",Type.DAMAGE),
	INDICATOR_ENTITY_DOLPHIN_DAMAGE("indicator.damage.dolphin",Type.DAMAGE),
	INDICATOR_ENTITY_DONKEY_DAMAGE("indicator.damage.donkey",Type.DAMAGE),
	INDICATOR_ENTITY_DROWNED_DAMAGE("indicator.damage.drowned",Type.DAMAGE),
	INDICATOR_ENTITY_ELDER_GUARDIAN_DAMAGE("indicator.damage.elderguardian",Type.DAMAGE),
	INDICATOR_ENTITY_ENDER_DRAGON_DAMAGE("indicator.damage.enderdragon",Type.DAMAGE),
	INDICATOR_ENTITY_ENDERMAN_DAMAGE("indicator.damage.enderman",Type.DAMAGE),
	INDICATOR_ENTITY_ENDERMITE_DAMAGE("indicator.damage.endermite",Type.DAMAGE),
	INDICATOR_ENTITY_EVOKER_DAMAGE("indicator.damage.evoker",Type.DAMAGE),
	INDICATOR_ENTITY_FOX_DAMAGE("indicator.damage.fox",Type.DAMAGE),
	INDICATOR_ENTITY_GHAST_DAMAGE("indicator.damage.ghast",Type.DAMAGE),
	INDICATOR_ENTITY_GIANT_DAMAGE("indicator.damage.giant",Type.DAMAGE),
	INDICATOR_ENTITY_GUARDIAN_DAMAGE("indicator.damage.guardian",Type.DAMAGE),
	INDICATOR_ENTITY_HOGLIN_DAMAGE("indicator.damage.hoglin",Type.DAMAGE),
	INDICATOR_ENTITY_HORSE_DAMAGE("indicator.damage.horse",Type.DAMAGE),
	INDICATOR_ENTITY_HUSK_DAMAGE("indicator.damage.husk",Type.DAMAGE),
	INDICATOR_ENTITY_ILLUSIONER_DAMAGE("indicator.damage.illusioner",Type.DAMAGE),
	INDICATOR_ENTITY_IRON_GOLEM_DAMAGE("indicator.damage.irongolem",Type.DAMAGE),
	INDICATOR_ENTITY_LLAMA_DAMAGE("indicator.damage.llama",Type.DAMAGE),
	INDICATOR_ENTITY_MAGMA_CUBE_DAMAGE("indicator.damage.magmacube",Type.DAMAGE),
	INDICATOR_ENTITY_MULE_DAMAGE("indicator.damage.mule",Type.DAMAGE),
	INDICATOR_ENTITY_MUSHROOM_COW_DAMAGE("indicator.damage.mushroomcow",Type.DAMAGE),
	INDICATOR_ENTITY_OCELOT_DAMAGE("indicator.damage.ocelot",Type.DAMAGE),
	INDICATOR_ENTITY_PANDA_DAMAGE("indicator.damage.panda",Type.DAMAGE),
	INDICATOR_ENTITY_PARROT_DAMAGE("indicator.damage.parrot",Type.DAMAGE),
	INDICATOR_ENTITY_PHANTOM_DAMAGE("indicator.damage.phantom",Type.DAMAGE),
	INDICATOR_ENTITY_PIG_DAMAGE("indicator.damage.pig",Type.DAMAGE),
	INDICATOR_ENTITY_PIGLIN_DAMAGE("indicator.damage.piglin",Type.DAMAGE),
	INDICATOR_ENTITY_PIGLIN_BRUTE_DAMAGE("indicator.damage.piglinbrute",Type.DAMAGE),
	INDICATOR_ENTITY_PIG_ZOMBIE_DAMAGE("indicator.damage.pigzombie",Type.DAMAGE),
	INDICATOR_ENTITY_PILLAGER_DAMAGE("indicator.damage.pillager",Type.DAMAGE),
	INDICATOR_ENTITY_POLAR_BEAR_DAMAGE("indicator.damage.polarbear",Type.DAMAGE),
	INDICATOR_ENTITY_PUFFERFISH_DAMAGE("indicator.damage.pufferfish",Type.DAMAGE),
	INDICATOR_ENTITY_RABBIT_DAMAGE("indicator.damage.rabbit",Type.DAMAGE),
	INDICATOR_ENTITY_RAVAGER_DAMAGE("indicator.damage.ravager",Type.DAMAGE),
	INDICATOR_ENTITY_SALMON_DAMAGE("indicator.damage.salmon",Type.DAMAGE),
	INDICATOR_ENTITY_SHEEP_DAMAGE("indicator.damage.sheep",Type.DAMAGE),
	INDICATOR_ENTITY_SHULKER_DAMAGE("indicator.damage.shulker",Type.DAMAGE),
	INDICATOR_ENTITY_SILVERFISH_DAMAGE("indicator.damage.silverfish",Type.DAMAGE),
	INDICATOR_ENTITY_SKELETON_DAMAGE("indicator.damage.skeleton",Type.DAMAGE),
	INDICATOR_ENTITY_SKELETON_HORSE_DAMAGE("indicator.damage.skeletonhorse",Type.DAMAGE),
	INDICATOR_ENTITY_SLIME_DAMAGE("indicator.damage.slime",Type.DAMAGE),
	INDICATOR_ENTITY_SNOWMAN_DAMAGE("indicator.damage.snowman",Type.DAMAGE),
	INDICATOR_ENTITY_SPIDER_DAMAGE("indicator.damage.spider",Type.DAMAGE),
	INDICATOR_ENTITY_SQUID_DAMAGE("indicator.damage.squid",Type.DAMAGE),
	INDICATOR_ENTITY_STRAY_DAMAGE("indicator.damage.stray",Type.DAMAGE),
	INDICATOR_ENTITY_STRIDER_DAMAGE("indicator.damage.strider",Type.DAMAGE),
	INDICATOR_ENTITY_TRADER_LLAMA_DAMAGE("indicator.damage.traderllama",Type.DAMAGE),
	INDICATOR_ENTITY_TROPICAL_FISH_DAMAGE("indicator.damage.tropicalfish",Type.DAMAGE),
	INDICATOR_ENTITY_TURTLE_DAMAGE("indicator.damage.turtle",Type.DAMAGE),
	INDICATOR_ENTITY_VEX_DAMAGE("indicator.damage.vex",Type.DAMAGE),
	INDICATOR_ENTITY_VILLAGER_DAMAGE("indicator.damage.villager",Type.DAMAGE),
	INDICATOR_ENTITY_VINDICATOR_DAMAGE("indicator.damage.vindicator",Type.DAMAGE),
	INDICATOR_ENTITY_WANDERING_TRADER_DAMAGE("indicator.damage.wanderingtrader",Type.DAMAGE),
	INDICATOR_ENTITY_WITCH_DAMAGE("indicator.damage.witch",Type.DAMAGE),
	INDICATOR_ENTITY_WITHER_DAMAGE("indicator.damage.wither",Type.DAMAGE),
	INDICATOR_ENTITY_WITHER_SKELETON_DAMAGE("indicator.damage.witherskeleton",Type.DAMAGE),
	INDICATOR_ENTITY_WOLF_DAMAGE("indicator.damage.wolf",Type.DAMAGE),
	INDICATOR_ENTITY_ZOGLIN_DAMAGE("indicator.damage.zoglin",Type.DAMAGE),
	INDICATOR_ENTITY_ZOMBIE_DAMAGE("indicator.damage.zombie",Type.DAMAGE),
	INDICATOR_ENTITY_ZOMBIE_HORSE_DAMAGE("indicator.damage.zombiehorse",Type.DAMAGE),
	INDICATOR_ENTITY_ZOMBIE_VILLAGER_DAMAGE("indicator.damage.zombievillager",Type.DAMAGE),
	INDICATOR_ENTITY_ZOMBIFIED_PIGLIN_DAMAGE("indicator.damage.zombifiedpiglin",Type.DAMAGE),
	BOSSBAR_ENTITY_UNKNOWN("bossbar.unknown",Type.BOSSBAR),
	BOSSBAR_ENTITY_PLAYER("bossbar.player",Type.BOSSBAR),
	BOSSBAR_ENTITY_BAT("bossbar.bat",Type.BOSSBAR),
	BOSSBAR_ENTITY_BEE("bossbar.bee",Type.BOSSBAR),
	BOSSBAR_ENTITY_BLAZE("bossbar.blaze",Type.BOSSBAR),
	BOSSBAR_ENTITY_CAT("bossbar.cat",Type.BOSSBAR),
	BOSSBAR_ENTITY_CAVE_SPIDER("bossbar.cavespider",Type.BOSSBAR),
	BOSSBAR_ENTITY_CHICKEN("bossbar.chicken",Type.BOSSBAR),
	BOSSBAR_ENTITY_COD("bossbar.cod",Type.BOSSBAR),
	BOSSBAR_ENTITY_COW("bossbar.cow",Type.BOSSBAR),
	BOSSBAR_ENTITY_CREEPER("bossbar.creeper",Type.BOSSBAR),
	BOSSBAR_ENTITY_DOLPHIN("bossbar.dolphin",Type.BOSSBAR),
	BOSSBAR_ENTITY_DONKEY("bossbar.donkey",Type.BOSSBAR),
	BOSSBAR_ENTITY_DROWNED("bossbar.drowned",Type.BOSSBAR),
	BOSSBAR_ENTITY_ELDER_GUARDIAN("bossbar.elderguardian",Type.BOSSBAR),
	BOSSBAR_ENTITY_ENDER_DRAGON("bossbar.enderdragon",Type.BOSSBAR),
	BOSSBAR_ENTITY_ENDERMAN("bossbar.enderman",Type.BOSSBAR),
	BOSSBAR_ENTITY_ENDERMITE("bossbar.endermite",Type.BOSSBAR),
	BOSSBAR_ENTITY_EVOKER("bossbar.evoker",Type.BOSSBAR),
	BOSSBAR_ENTITY_FOX("bossbar.fox",Type.BOSSBAR),
	BOSSBAR_ENTITY_GHAST("bossbar.ghast",Type.BOSSBAR),
	BOSSBAR_ENTITY_GIANT("bossbar.giant",Type.BOSSBAR),
	BOSSBAR_ENTITY_GUARDIAN("bossbar.guardian",Type.BOSSBAR),
	BOSSBAR_ENTITY_HOGLIN("bossbar.hoglin",Type.BOSSBAR),
	BOSSBAR_ENTITY_HORSE("bossbar.horse",Type.BOSSBAR),
	BOSSBAR_ENTITY_HUSK("bossbar.husk",Type.BOSSBAR),
	BOSSBAR_ENTITY_ILLUSIONER("bossbar.illusioner",Type.BOSSBAR),
	BOSSBAR_ENTITY_IRON_GOLEM("bossbar.irongolem",Type.BOSSBAR),
	BOSSBAR_ENTITY_LLAMA("bossbar.llama",Type.BOSSBAR),
	BOSSBAR_ENTITY_MAGMA_CUBE("bossbar.magmacube",Type.BOSSBAR),
	BOSSBAR_ENTITY_MULE("bossbar.mule",Type.BOSSBAR),
	BOSSBAR_ENTITY_MUSHROOM_COW("bossbar.mushroomcow",Type.BOSSBAR),
	BOSSBAR_ENTITY_OCELOT("bossbar.ocelot",Type.BOSSBAR),
	BOSSBAR_ENTITY_PANDA("bossbar.panda",Type.BOSSBAR),
	BOSSBAR_ENTITY_PARROT("bossbar.parrot",Type.BOSSBAR),
	BOSSBAR_ENTITY_PHANTOM("bossbar.phantom",Type.BOSSBAR),
	BOSSBAR_ENTITY_PIG("bossbar.pig",Type.BOSSBAR),
	BOSSBAR_ENTITY_PIGLIN("bossbar.piglin",Type.BOSSBAR),
	BOSSBAR_ENTITY_PIGLIN_BRUTE("bossbar.piglinbrute",Type.BOSSBAR),
	BOSSBAR_ENTITY_PIG_ZOMBIE("bossbar.pigzombie",Type.BOSSBAR),
	BOSSBAR_ENTITY_PILLAGER("bossbar.pillager",Type.BOSSBAR),
	BOSSBAR_ENTITY_POLAR_BEAR("bossbar.polarbear",Type.BOSSBAR),
	BOSSBAR_ENTITY_PUFFERFISH("bossbar.pufferfish",Type.BOSSBAR),
	BOSSBAR_ENTITY_RABBIT("bossbar.rabbit",Type.BOSSBAR),
	BOSSBAR_ENTITY_RAVAGER("bossbar.ravager",Type.BOSSBAR),
	BOSSBAR_ENTITY_SALMON("bossbar.salmon",Type.BOSSBAR),
	BOSSBAR_ENTITY_SHEEP("bossbar.sheep",Type.BOSSBAR),
	BOSSBAR_ENTITY_SHULKER("bossbar.shulker",Type.BOSSBAR),
	BOSSBAR_ENTITY_SILVERFISH("bossbar.silverfish",Type.BOSSBAR),
	BOSSBAR_ENTITY_SKELETON("bossbar.skeleton",Type.BOSSBAR),
	BOSSBAR_ENTITY_SKELETON_HORSE("bossbar.skeletonhorse",Type.BOSSBAR),
	BOSSBAR_ENTITY_SLIME("bossbar.slime",Type.BOSSBAR),
	BOSSBAR_ENTITY_SNOWMAN("bossbar.snowman",Type.BOSSBAR),
	BOSSBAR_ENTITY_SPIDER("bossbar.spider",Type.BOSSBAR),
	BOSSBAR_ENTITY_SQUID("bossbar.squid",Type.BOSSBAR),
	BOSSBAR_ENTITY_STRAY("bossbar.stray",Type.BOSSBAR),
	BOSSBAR_ENTITY_STRIDER("bossbar.strider",Type.BOSSBAR),
	BOSSBAR_ENTITY_TRADER_LLAMA("bossbar.traderllama",Type.BOSSBAR),
	BOSSBAR_ENTITY_TROPICAL_FISH("bossbar.tropicalfish",Type.BOSSBAR),
	BOSSBAR_ENTITY_TURTLE("bossbar.turtle",Type.BOSSBAR),
	BOSSBAR_ENTITY_VEX("bossbar.vex",Type.BOSSBAR),
	BOSSBAR_ENTITY_VILLAGER("bossbar.villager",Type.BOSSBAR),
	BOSSBAR_ENTITY_VINDICATOR("bossbar.vindicator",Type.BOSSBAR),
	BOSSBAR_ENTITY_WANDERING_TRADER("bossbar.wanderingtrader",Type.BOSSBAR),
	BOSSBAR_ENTITY_WITCH("bossbar.witch",Type.BOSSBAR),
	BOSSBAR_ENTITY_WITHER("bossbar.wither",Type.BOSSBAR),
	BOSSBAR_ENTITY_WITHER_SKELETON("bossbar.witherskeleton",Type.BOSSBAR),
	BOSSBAR_ENTITY_WOLF("bossbar.wolf",Type.BOSSBAR),
	BOSSBAR_ENTITY_ZOGLIN("bossbar.zoglin",Type.BOSSBAR),
	BOSSBAR_ENTITY_ZOMBIE("bossbar.zombie",Type.BOSSBAR),
	BOSSBAR_ENTITY_ZOMBIE_HORSE("bossbar.zombiehorse",Type.BOSSBAR),
	BOSSBAR_ENTITY_ZOMBIE_VILLAGER("bossbar.zombievillager",Type.BOSSBAR),
	BOSSBAR_ENTITY_ZOMBIFIED_PIGLIN("bossbar.zombifiedpiglin",Type.BOSSBAR);
	private LangMsg(String configkey,Type type) {
		this.configkey = configkey;
		this.type = type;
	}
	private String configkey;
	private Type type;
	protected String getKey() {
		return configkey;
	}
	protected Type getType() {
		return type;
	}
	protected static LangMsg getMessage(EntityType entitytype,Type type) {
		switch (type) {
		case BOSSBAR : return getBossbar(entitytype);
		case DAMAGE : return getIndicatorDamage(entitytype);
		case HEAL : return getIndicatorHeal(entitytype);
		}
		return null;
	}
	private static LangMsg getIndicatorHeal(EntityType entitytype) {
		switch(entitytype) {
		case PLAYER : return INDICATOR_ENTITY_PLAYER_HEAL;
		case BAT : return INDICATOR_ENTITY_BAT_HEAL;
		case BEE : return INDICATOR_ENTITY_BEE_HEAL;
		case BLAZE : return INDICATOR_ENTITY_BLAZE_HEAL;
		case CAT : return INDICATOR_ENTITY_CAT_HEAL;
		case CAVE_SPIDER : return INDICATOR_ENTITY_CAVE_SPIDER_HEAL;
		case CHICKEN : return INDICATOR_ENTITY_CHICKEN_HEAL;
		case COD : return INDICATOR_ENTITY_COD_HEAL;
		case COW : return INDICATOR_ENTITY_COW_HEAL;
		case CREEPER : return INDICATOR_ENTITY_CREEPER_HEAL;
		case DOLPHIN : return INDICATOR_ENTITY_DOLPHIN_HEAL;
		case DONKEY : return INDICATOR_ENTITY_DONKEY_HEAL;
		case DROWNED : return INDICATOR_ENTITY_DROWNED_HEAL;
		case ELDER_GUARDIAN : return INDICATOR_ENTITY_ELDER_GUARDIAN_HEAL;
		case ENDER_DRAGON : return INDICATOR_ENTITY_ENDER_DRAGON_HEAL;
		case ENDERMAN : return INDICATOR_ENTITY_ENDERMAN_HEAL;
		case ENDERMITE : return INDICATOR_ENTITY_ENDERMITE_HEAL;
		case EVOKER : return INDICATOR_ENTITY_EVOKER_HEAL;
		case FOX : return INDICATOR_ENTITY_FOX_HEAL;
		case GHAST : return INDICATOR_ENTITY_GHAST_HEAL;
		case GIANT : return INDICATOR_ENTITY_GIANT_HEAL;
		case GUARDIAN : return INDICATOR_ENTITY_GUARDIAN_HEAL;
		case HOGLIN : return INDICATOR_ENTITY_HOGLIN_HEAL;
		case HORSE : return INDICATOR_ENTITY_HORSE_HEAL;
		case HUSK : return INDICATOR_ENTITY_HUSK_HEAL;
		case ILLUSIONER : return INDICATOR_ENTITY_ILLUSIONER_HEAL;
		case IRON_GOLEM : return INDICATOR_ENTITY_IRON_GOLEM_HEAL;
		case LLAMA : return INDICATOR_ENTITY_LLAMA_HEAL;
		case MAGMA_CUBE : return INDICATOR_ENTITY_MAGMA_CUBE_HEAL;
		case MULE : return INDICATOR_ENTITY_MULE_HEAL;
		case MUSHROOM_COW : return INDICATOR_ENTITY_MUSHROOM_COW_HEAL;
		case OCELOT : return INDICATOR_ENTITY_OCELOT_HEAL;
		case PANDA : return INDICATOR_ENTITY_PANDA_HEAL;
		case PARROT : return INDICATOR_ENTITY_PARROT_HEAL;
		case PHANTOM : return INDICATOR_ENTITY_PHANTOM_HEAL;
		case PIG : return INDICATOR_ENTITY_PIG_HEAL;
		case PIGLIN : return INDICATOR_ENTITY_PIGLIN_HEAL;
		case PIGLIN_BRUTE : return INDICATOR_ENTITY_PIGLIN_BRUTE_HEAL;
		case PIG_ZOMBIE : return INDICATOR_ENTITY_PIG_ZOMBIE_HEAL;
		case PILLAGER : return INDICATOR_ENTITY_PILLAGER_HEAL;
		case POLAR_BEAR : return INDICATOR_ENTITY_POLAR_BEAR_HEAL;
		case PUFFERFISH : return INDICATOR_ENTITY_PUFFERFISH_HEAL;
		case RABBIT : return INDICATOR_ENTITY_RABBIT_HEAL;
		case RAVAGER : return INDICATOR_ENTITY_RAVAGER_HEAL;
		case SALMON : return INDICATOR_ENTITY_SALMON_HEAL;
		case SHEEP : return INDICATOR_ENTITY_SHEEP_HEAL;
		case SHULKER : return INDICATOR_ENTITY_SHULKER_HEAL;
		case SILVERFISH : return INDICATOR_ENTITY_SILVERFISH_HEAL;
		case SKELETON : return INDICATOR_ENTITY_SKELETON_HEAL;
		case SKELETON_HORSE : return INDICATOR_ENTITY_SKELETON_HORSE_HEAL;
		case SLIME : return INDICATOR_ENTITY_SLIME_HEAL;
		case SNOWMAN : return INDICATOR_ENTITY_SNOWMAN_HEAL;
		case SPIDER : return INDICATOR_ENTITY_SPIDER_HEAL;
		case SQUID : return INDICATOR_ENTITY_SQUID_HEAL;
		case STRAY : return INDICATOR_ENTITY_STRAY_HEAL;
		case STRIDER : return INDICATOR_ENTITY_STRIDER_HEAL;
		case TRADER_LLAMA : return INDICATOR_ENTITY_TRADER_LLAMA_HEAL;
		case TROPICAL_FISH : return INDICATOR_ENTITY_TROPICAL_FISH_HEAL;
		case TURTLE : return INDICATOR_ENTITY_TURTLE_HEAL;
		case VEX : return INDICATOR_ENTITY_VEX_HEAL;
		case VILLAGER : return INDICATOR_ENTITY_VILLAGER_HEAL;
		case VINDICATOR : return INDICATOR_ENTITY_VINDICATOR_HEAL;
		case WANDERING_TRADER : return INDICATOR_ENTITY_WANDERING_TRADER_HEAL;
		case WITCH : return INDICATOR_ENTITY_WITCH_HEAL;
		case WITHER : return INDICATOR_ENTITY_WITHER_HEAL;
		case WITHER_SKELETON : return INDICATOR_ENTITY_WITHER_SKELETON_HEAL;
		case WOLF : return INDICATOR_ENTITY_WOLF_HEAL;
		case ZOGLIN : return INDICATOR_ENTITY_ZOGLIN_HEAL;
		case ZOMBIE : return INDICATOR_ENTITY_ZOMBIE_HEAL;
		case ZOMBIE_HORSE : return INDICATOR_ENTITY_ZOMBIE_HORSE_HEAL;
		case ZOMBIE_VILLAGER : return INDICATOR_ENTITY_ZOMBIE_VILLAGER_HEAL;
		case ZOMBIFIED_PIGLIN : return INDICATOR_ENTITY_ZOMBIFIED_PIGLIN_HEAL;
		default : return INDICATOR_ENTITY_UNKNOWN_HEAL;
		}
	}
	private static LangMsg getIndicatorDamage(EntityType entitytype) {
		switch(entitytype) {
		case PLAYER : return INDICATOR_ENTITY_PLAYER_DAMAGE;
		case BAT : return INDICATOR_ENTITY_BAT_DAMAGE;
		case BEE : return INDICATOR_ENTITY_BEE_DAMAGE;
		case BLAZE : return INDICATOR_ENTITY_BLAZE_DAMAGE;
		case CAT : return INDICATOR_ENTITY_CAT_DAMAGE;
		case CAVE_SPIDER : return INDICATOR_ENTITY_CAVE_SPIDER_DAMAGE;
		case CHICKEN : return INDICATOR_ENTITY_CHICKEN_DAMAGE;
		case COD : return INDICATOR_ENTITY_COD_DAMAGE;
		case COW : return INDICATOR_ENTITY_COW_DAMAGE;
		case CREEPER : return INDICATOR_ENTITY_CREEPER_DAMAGE;
		case DOLPHIN : return INDICATOR_ENTITY_DOLPHIN_DAMAGE;
		case DONKEY : return INDICATOR_ENTITY_DONKEY_DAMAGE;
		case DROWNED : return INDICATOR_ENTITY_DROWNED_DAMAGE;
		case ELDER_GUARDIAN : return INDICATOR_ENTITY_ELDER_GUARDIAN_DAMAGE;
		case ENDER_DRAGON : return INDICATOR_ENTITY_ENDER_DRAGON_DAMAGE;
		case ENDERMAN : return INDICATOR_ENTITY_ENDERMAN_DAMAGE;
		case ENDERMITE : return INDICATOR_ENTITY_ENDERMITE_DAMAGE;
		case EVOKER : return INDICATOR_ENTITY_EVOKER_DAMAGE;
		case FOX : return INDICATOR_ENTITY_FOX_DAMAGE;
		case GHAST : return INDICATOR_ENTITY_GHAST_DAMAGE;
		case GIANT : return INDICATOR_ENTITY_GIANT_DAMAGE;
		case GUARDIAN : return INDICATOR_ENTITY_GUARDIAN_DAMAGE;
		case HOGLIN : return INDICATOR_ENTITY_HOGLIN_DAMAGE;
		case HORSE : return INDICATOR_ENTITY_HORSE_DAMAGE;
		case HUSK : return INDICATOR_ENTITY_HUSK_DAMAGE;
		case ILLUSIONER : return INDICATOR_ENTITY_ILLUSIONER_DAMAGE;
		case IRON_GOLEM : return INDICATOR_ENTITY_IRON_GOLEM_DAMAGE;
		case LLAMA : return INDICATOR_ENTITY_LLAMA_DAMAGE;
		case MAGMA_CUBE : return INDICATOR_ENTITY_MAGMA_CUBE_DAMAGE;
		case MULE : return INDICATOR_ENTITY_MULE_DAMAGE;
		case MUSHROOM_COW : return INDICATOR_ENTITY_MUSHROOM_COW_DAMAGE;
		case OCELOT : return INDICATOR_ENTITY_OCELOT_DAMAGE;
		case PANDA : return INDICATOR_ENTITY_PANDA_DAMAGE;
		case PARROT : return INDICATOR_ENTITY_PARROT_DAMAGE;
		case PHANTOM : return INDICATOR_ENTITY_PHANTOM_DAMAGE;
		case PIG : return INDICATOR_ENTITY_PIG_DAMAGE;
		case PIGLIN : return INDICATOR_ENTITY_PIGLIN_DAMAGE;
		case PIGLIN_BRUTE : return INDICATOR_ENTITY_PIGLIN_BRUTE_DAMAGE;
		case PIG_ZOMBIE : return INDICATOR_ENTITY_PIG_ZOMBIE_DAMAGE;
		case PILLAGER : return INDICATOR_ENTITY_PILLAGER_DAMAGE;
		case POLAR_BEAR : return INDICATOR_ENTITY_POLAR_BEAR_DAMAGE;
		case PUFFERFISH : return INDICATOR_ENTITY_PUFFERFISH_DAMAGE;
		case RABBIT : return INDICATOR_ENTITY_RABBIT_DAMAGE;
		case RAVAGER : return INDICATOR_ENTITY_RAVAGER_DAMAGE;
		case SALMON : return INDICATOR_ENTITY_SALMON_DAMAGE;
		case SHEEP : return INDICATOR_ENTITY_SHEEP_DAMAGE;
		case SHULKER : return INDICATOR_ENTITY_SHULKER_DAMAGE;
		case SILVERFISH : return INDICATOR_ENTITY_SILVERFISH_DAMAGE;
		case SKELETON : return INDICATOR_ENTITY_SKELETON_DAMAGE;
		case SKELETON_HORSE : return INDICATOR_ENTITY_SKELETON_HORSE_DAMAGE;
		case SLIME : return INDICATOR_ENTITY_SLIME_DAMAGE;
		case SNOWMAN : return INDICATOR_ENTITY_SNOWMAN_DAMAGE;
		case SPIDER : return INDICATOR_ENTITY_SPIDER_DAMAGE;
		case SQUID : return INDICATOR_ENTITY_SQUID_DAMAGE;
		case STRAY : return INDICATOR_ENTITY_STRAY_DAMAGE;
		case STRIDER : return INDICATOR_ENTITY_STRIDER_DAMAGE;
		case TRADER_LLAMA : return INDICATOR_ENTITY_TRADER_LLAMA_DAMAGE;
		case TROPICAL_FISH : return INDICATOR_ENTITY_TROPICAL_FISH_DAMAGE;
		case TURTLE : return INDICATOR_ENTITY_TURTLE_DAMAGE;
		case VEX : return INDICATOR_ENTITY_VEX_DAMAGE;
		case VILLAGER : return INDICATOR_ENTITY_VILLAGER_DAMAGE;
		case VINDICATOR : return INDICATOR_ENTITY_VINDICATOR_DAMAGE;
		case WANDERING_TRADER : return INDICATOR_ENTITY_WANDERING_TRADER_DAMAGE;
		case WITCH : return INDICATOR_ENTITY_WITCH_DAMAGE;
		case WITHER : return INDICATOR_ENTITY_WITHER_DAMAGE;
		case WITHER_SKELETON : return INDICATOR_ENTITY_WITHER_SKELETON_DAMAGE;
		case WOLF : return INDICATOR_ENTITY_WOLF_DAMAGE;
		case ZOGLIN : return INDICATOR_ENTITY_ZOGLIN_DAMAGE;
		case ZOMBIE : return INDICATOR_ENTITY_ZOMBIE_DAMAGE;
		case ZOMBIE_HORSE : return INDICATOR_ENTITY_ZOMBIE_HORSE_DAMAGE;
		case ZOMBIE_VILLAGER : return INDICATOR_ENTITY_ZOMBIE_VILLAGER_DAMAGE;
		case ZOMBIFIED_PIGLIN : return INDICATOR_ENTITY_ZOMBIFIED_PIGLIN_DAMAGE;
		default : return INDICATOR_ENTITY_UNKNOWN_DAMAGE;
		}
	}
	private static LangMsg getBossbar(EntityType entitytype) {
		switch(entitytype) {
		case PLAYER : return BOSSBAR_ENTITY_PLAYER;
		case BAT : return BOSSBAR_ENTITY_BAT;
		case BEE : return BOSSBAR_ENTITY_BEE;
		case BLAZE : return BOSSBAR_ENTITY_BLAZE;
		case CAT : return BOSSBAR_ENTITY_CAT;
		case CAVE_SPIDER : return BOSSBAR_ENTITY_CAVE_SPIDER;
		case CHICKEN : return BOSSBAR_ENTITY_CHICKEN;
		case COD : return BOSSBAR_ENTITY_COD;
		case COW : return BOSSBAR_ENTITY_COW;
		case CREEPER : return BOSSBAR_ENTITY_CREEPER;
		case DOLPHIN : return BOSSBAR_ENTITY_DOLPHIN;
		case DONKEY : return BOSSBAR_ENTITY_DONKEY;
		case DROWNED : return BOSSBAR_ENTITY_DROWNED;
		case ELDER_GUARDIAN : return BOSSBAR_ENTITY_ELDER_GUARDIAN;
		case ENDER_DRAGON : return BOSSBAR_ENTITY_ENDER_DRAGON;
		case ENDERMAN : return BOSSBAR_ENTITY_ENDERMAN;
		case ENDERMITE : return BOSSBAR_ENTITY_ENDERMITE;
		case EVOKER : return BOSSBAR_ENTITY_EVOKER;
		case FOX : return BOSSBAR_ENTITY_FOX;
		case GHAST : return BOSSBAR_ENTITY_GHAST;
		case GIANT : return BOSSBAR_ENTITY_GIANT;
		case GUARDIAN : return BOSSBAR_ENTITY_GUARDIAN;
		case HOGLIN : return BOSSBAR_ENTITY_HOGLIN;
		case HORSE : return BOSSBAR_ENTITY_HORSE;
		case HUSK : return BOSSBAR_ENTITY_HUSK;
		case ILLUSIONER : return BOSSBAR_ENTITY_ILLUSIONER;
		case IRON_GOLEM : return BOSSBAR_ENTITY_IRON_GOLEM;
		case LLAMA : return BOSSBAR_ENTITY_LLAMA;
		case MAGMA_CUBE : return BOSSBAR_ENTITY_MAGMA_CUBE;
		case MULE : return BOSSBAR_ENTITY_MULE;
		case MUSHROOM_COW : return BOSSBAR_ENTITY_MUSHROOM_COW;
		case OCELOT : return BOSSBAR_ENTITY_OCELOT;
		case PANDA : return BOSSBAR_ENTITY_PANDA;
		case PARROT : return BOSSBAR_ENTITY_PARROT;
		case PHANTOM : return BOSSBAR_ENTITY_PHANTOM;
		case PIG : return BOSSBAR_ENTITY_PIG;
		case PIGLIN : return BOSSBAR_ENTITY_PIGLIN;
		case PIGLIN_BRUTE : return BOSSBAR_ENTITY_PIGLIN_BRUTE;
		case PIG_ZOMBIE : return BOSSBAR_ENTITY_PIG_ZOMBIE;
		case PILLAGER : return BOSSBAR_ENTITY_PILLAGER;
		case POLAR_BEAR : return BOSSBAR_ENTITY_POLAR_BEAR;
		case PUFFERFISH : return BOSSBAR_ENTITY_PUFFERFISH;
		case RABBIT : return BOSSBAR_ENTITY_RABBIT;
		case RAVAGER : return BOSSBAR_ENTITY_RAVAGER;
		case SALMON : return BOSSBAR_ENTITY_SALMON;
		case SHEEP : return BOSSBAR_ENTITY_SHEEP;
		case SHULKER : return BOSSBAR_ENTITY_SHULKER;
		case SILVERFISH : return BOSSBAR_ENTITY_SILVERFISH;
		case SKELETON : return BOSSBAR_ENTITY_SKELETON;
		case SKELETON_HORSE : return BOSSBAR_ENTITY_SKELETON_HORSE;
		case SLIME : return BOSSBAR_ENTITY_SLIME;
		case SNOWMAN : return BOSSBAR_ENTITY_SNOWMAN;
		case SPIDER : return BOSSBAR_ENTITY_SPIDER;
		case SQUID : return BOSSBAR_ENTITY_SQUID;
		case STRAY : return BOSSBAR_ENTITY_STRAY;
		case STRIDER : return BOSSBAR_ENTITY_STRIDER;
		case TRADER_LLAMA : return BOSSBAR_ENTITY_TRADER_LLAMA;
		case TROPICAL_FISH : return BOSSBAR_ENTITY_TROPICAL_FISH;
		case TURTLE : return BOSSBAR_ENTITY_TURTLE;
		case VEX : return BOSSBAR_ENTITY_VEX;
		case VILLAGER : return BOSSBAR_ENTITY_VILLAGER;
		case VINDICATOR : return BOSSBAR_ENTITY_VINDICATOR;
		case WANDERING_TRADER : return BOSSBAR_ENTITY_WANDERING_TRADER;
		case WITCH : return BOSSBAR_ENTITY_WITCH;
		case WITHER : return BOSSBAR_ENTITY_WITHER;
		case WITHER_SKELETON : return BOSSBAR_ENTITY_WITHER_SKELETON;
		case WOLF : return BOSSBAR_ENTITY_WOLF;
		case ZOGLIN : return BOSSBAR_ENTITY_ZOGLIN;
		case ZOMBIE : return BOSSBAR_ENTITY_ZOMBIE;
		case ZOMBIE_HORSE : return BOSSBAR_ENTITY_ZOMBIE_HORSE;
		case ZOMBIE_VILLAGER : return BOSSBAR_ENTITY_ZOMBIE_VILLAGER;
		case ZOMBIFIED_PIGLIN : return BOSSBAR_ENTITY_ZOMBIFIED_PIGLIN;
		default : return BOSSBAR_ENTITY_UNKNOWN;
		}
	}
	enum Type {
		HEAL,
		DAMAGE,
		BOSSBAR;
	}
}
